name: NaturalDisastersWrapper
version: '1.0'
main: com.NaturalDisastersWrapper.core.NaturalDisastersWrapper
api-version: '1.20'
load: STARTUP
description: A wrapper for the natural disasters mod
author: JonTGN
commands:
  test:
    description: test command
