name: NaturalDisastersWrapper
version: '1.0'
main: com.NaturalDisastersWrapper.core.NaturalDisastersWrapper
api-version: '1.20'
load: STARTUP
description: A wrapper for the natural disasters mod
author: JonTGN
commands:
  ndw:
    description: Gives the player a one-time-use item with a custom material, name, and command.
    usage: /ndw <material> <custom_name> <command>
